config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :users do
    resources :posts do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_one :comment, as: :commentable

  scope :order_by_recent, -> { order(created_at: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable

  validates :description, presence: true
  validates :title, presence: true

  scope :order_by_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  def after_sign_in_path_for(resource)
    users_posts_path #your path
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  def create
    @comment= current_user.comments.new(comment_params)
    params[:commentable_id].present? ? set_commentable(params[:commentable_id], 'Comment') : set_commentable(params[:post_id], 'Post')
    @comment.save!
  end

  private

  def set_commentable(id, type)
    @comment.commentable_id = id
    @comment.commentable_type = type
  end

  def comment_params
    params.permit(:description)
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController

  def index
    @posts = Post.order_by_recent.paginate(page: params[:page], per_page: 10)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments.order_by_recent
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save 
      flash[:success] = "Blog has been created successfuly"
      redirect_to users_posts_path
    else
      flash[:error] = @post.errors.full_messages.join("<br/>").html_safe
      redirect_to new_users_post_path
    end
  end

  private

  def post_params
    params.permit(:description, :title)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  private

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <h3> Blog App</h3>
    <% end %>
    <form class="d-flex">
      <% if current_user %>
        <%= link_to 'Home', users_posts_path, class: 'btn custom-button' %>
        <%= link_to 'Add Blog', new_users_post_path, class: 'btn custom-button' %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: "delete", class: 'btn custom-button' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: 'btn custom-button'%>
        <%= link_to "Login", new_user_session_path, class: 'btn custom-button' %>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: '/layouts/header' %>
    <div class="main-container">
      <%= yield %>
    </div>
    <%= render partial: '/shared/flash_messages' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']("<%= value.html_safe %>")
    <% end %>
  </script>
<% end %>

app/views/users/comments/create.js.erb
$("#comments-container").load(window.location.href+" #comments-container");

app/views/users/posts/_form.html.erb
<%= form_with(model: comment, url: users_post_comments_path(post.id), remote:true) do |f| %>
  <%= f.label :add_comment %>
  <p><%= f.text_area :description, required: true, class:"form-control", placeholder: "write comments here... "  %></p>
  <p><%= f.submit "comment",class: "btn btn-success" %></p>
<%end%>

app/views/users/posts/_list.html.erb
<p><h3> Blogs </h3></p>
<% if posts.present? %>
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col">Blog By</th>
        <th scope="col">Created On</th>
        <th scope="col">Title</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    
    <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.created_at %></td>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', users_post_path(post.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<%end%>

app/views/users/posts/_reply_form.html.erb
<%= form_with(model: comment, url: users_post_comments_path(post.id), remote:true) do |f| %>
  <p><%= f.text_area :description, required: true, class:"form-control", placeholder: "write comments here... "  %></p>
  <%= f.hidden_field :commentable_id, value: commentable_id%>
  <p><%= f.submit "Reply",class: "btn btn-dark " %></p>
<%end%>

app/views/users/posts/index.html.erb
<%= render partial: 'list', locals: { posts: @posts } %>
<div class="custom_pagination">
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/users/posts/new.html.erb
<div class="container" style="margin-top: 30px;">
  <%= form_with model: @post, local: true, url: users_posts_path do |f| %>
    <%= f.label :title %>
    <p><%= f.text_field :title, class: "form-control"%></p>
    <p><%= f.text_area :description, class: "form-control", placeholder: "Blog content", rows: 15 %></p>
    <p><%= f.submit "Add Blog",class: "btn btn-success" %></p>
  <%end%>
</div>

app/views/users/posts/show.html.erb
<div class="container">
  <p><h3> <%= @post.title %> </h3></p>  
  <p><br><%= @post.description %></br></p>
  <div class="comment-form">
    <%= render partial: 'form', locals: { post: @post, comment: @comment }%>
  </div>

  <div id ="comments-container">
    <%= @comments.size %> comments   <br></br>
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <div class="comment span">
          <%= image_tag("icon.jpeg", :size => "20x20") %>
          <span><%= comment.user.email %></span>
          <br><%= comment.description %></br>
          <span><%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></span>
          <p>
            <div class="nested-form">
              <% if comment.comment %>
                <%= comment.comment.description %>
                <%= image_tag("icon.jpeg", :size => "20x20") %>
                <span><%= @post.user.email %></span>
              <% elsif current_user.eql?(@post.user)%>
                  <%= render partial: 'reply_form', locals: { post: @post, comment: @comment, commentable_id: comment.id }%>
              <%end%>
            </div>
          </p>
          <hr>
        </div>
      <%end%>
    <% end %>
  </div>
</div>

<style type="text/css">
  .comment{
    margin-left: 15px;
  }

  .comment span{
    color: grey;
  }

  .nested-form{
    margin-left: 30px;
  }
</style>

app/views/welcome/index.html.erb
<h1>Welcome page!</h1>
<%= link_to "Sign up", new_user_registration_path %> |
<%= link_to "Login", new_user_session_path  %>